### ISSUE TITLE
error "no active game was found" when valid game was playing at TCEC, in the middle of game

### ISSUE THREAD

**Issue by Paul-T-pdx** [NikolayIT/TcecEvaluationBot#2]
error "no active game was found" when valid game was playing at TCEC, in the middle of game.
Also, it was Mark Lefter himself who tried !eval and got such error. What luck!
So, I presume when Eval Bot tried to fetch FEN for evaluation, for some reason there was no response from TCEC server. that's why "no active game was found". 
It should re-try to fetch for FEN, and issue fail message only after many re-tries.

**Comment by NikolayIT** [comment]
Fixed it by replacing 32-bit komodo with 64-bit komodo.
