### ISSUE TITLE
Feature request: Add a command to display the estimated starting time of the next game

### ISSUE THREAD

**Issue by gvreuls** [NikolayIT/TcecEvaluationBot#6]
The bot already displays the estimated starting time of an upcoming game with the `!time <game number>` command, but twitch viewers don't have access to the TCEC schedule so there is no easy way for them to tell the game number of the current (or any other) game.

JamesTCEC suggested a `!nextgame` command for the bot with the same effect as a `!time <current game number> + 1`. (The command should preferably be called `!nextgame` because `!next` is already taken by Nightbot.)

**Comment by NikolayIT** [comment]
What about `!time next`

**Comment by gvreuls** [comment]
That's even better :)

**Comment by NikolayIT** [comment]
Ok you have it now. 😄 

    NikolayIT: !time next
    TCEC_Evaluation: [15:00:49] Game "Fizbo 2" vs "Andscacs 0.93" is estimated to start on Tue, 13 Mar 2018 16:58:31 GMT
    NikolayIT: !time last
    TCEC_Evaluation: [15:01:21] Game "Houdini 6.03" vs "Komodo 2012.00" finished with result "1 0"

**Comment by gvreuls** [comment]
Thanks a lot, this must be the fastest feature implementation in the history of github.
