### ISSUE TITLE
Wrong castle notation 

### ISSUE THREAD

**Issue by NikolayIT** [NikolayIT/TcecEvaluationBot#9]
It gives `Kxg8` instead of `O-O`, quote: `eval_bot (13w) 1.04 d31 (tb 4) pv Qf2(g3f2) Kxg8(e8g8) <SF_240518>`

**Comment by noobpwnftw** [comment]
https://github.com/NikolayIT/TcecEvaluationBot/blob/f528b50410ec4aa34d9494ca03be62cf9d002e31/src/TcecEvaluationBot.ConsoleUI/Services/MoveConversionService.cs#L72

Here you might want to add:
`case MoveType.Move | MoveType.Castling:`

since a castling move has both flags.
